# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-25 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supply', '0001_initial'),
        ('meetingroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('amount_of_people', models.IntegerField(blank=True)),
                ('meetingroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingroom_bookmr', to='meetingroom.MeetingRoom')),
                ('supplies', models.ManyToManyField(to='supply.Supply')),
            ],
        ),
    ]
